name: Deploy to Server

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build release artifact
        run: |
          mkdir -p release
          rsync -a compu-import-lego/ release/compu-import-lego/
          cp -a compu-run-02-06_v3.6.sh release/
          tar -C release -czf release.tar.gz .

      - name: Setup SSH agent (load private key)
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Ensure target directory exists
        run: |
          ssh -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "mkdir -p '${{ secrets.DEPLOY_PATH }}'"

      - name: Upload release to server
        run: |
          scp -P "${{ secrets.SSH_PORT }}" -o StrictHostKeyChecking=yes \
            release.tar.gz "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}/release.tar.gz"

      - name: Unpack on server
        run: |
          ssh -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" \
            "tar -C '${{ secrets.DEPLOY_PATH }}' -xzf '${{ secrets.DEPLOY_PATH }}/release.tar.gz'"

      - name: Run remote deploy (with smoke test)
        run: |
          ssh -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" \
            "/home/compustar/deploy/deploy.sh '${{ secrets.DEPLOY_PATH }}/release'"
