name: Deploy to Server

on:
  push:
    branches: [ "main" ]   # despliega en cada push a main
  workflow_dispatch:        # permite ejecutarlo manualmente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build release artifact
        run: |
          mkdir -p release
          rsync -a compu-import-lego/ release/compu-import-lego/
          cp -a compu-run-02-06_v3.6.sh release/
          tar -C release -czf release.tar.gz .

      # Carga la clave privada (Deploy Key)
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      # Agrega known_hosts (del servidor compustar.mx)
      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      # Sube el release al servidor
      - name: Upload release tarball
        run: |
          scp -o StrictHostKeyChecking=yes release.tar.gz \
            ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/home/compustar/releases/${{ github.sha }}.tar.gz

      # Desempaqueta en /home/compustar/releases/<sha>
      - name: Unpack on server
        run: |
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} \
            "mkdir -p /home/compustar/releases/${{ github.sha }} && \
             tar -C /home/compustar/releases/${{ github.sha }} -xzf /home/compustar/releases/${{ github.sha }}.tar.gz"

      # Ejecuta el deploy con smoke test (usa /home/compustar/deploy/deploy.sh del servidor)
      - name: Run remote deploy (with smoke test)
        run: |
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} \
            "/home/compustar/deploy/deploy.sh /home/compustar/releases/${{ github.sha }}"
