name: Deploy to Server

on:
  push:
    branches: [ main ]      # despliega en cada push a main
  workflow_dispatch:         # permite ejecutarlo manualmente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH agent (load private key)
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # No usamos known_hosts para evitar errores con $HOME vacío.
      - name: Skip known_hosts (info)
        run: echo "Using SSH with -o StrictHostKeyChecking=no"

      - name: Ensure target directory exists
        run: |
          DEST="${{ secrets.DEPLOY_PATH }}"
          if [ -z "$DEST" ]; then DEST="/root/compustar-deploy"; fi
          ssh -o StrictHostKeyChecking=no -p "${{ secrets.SSH_PORT }}" \
            "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" \
            "mkdir -p \"$DEST\" && echo DEST OK: $DEST"

      - name: Rsync files to server
        run: |
          DEST="${{ secrets.DEPLOY_PATH }}"
          if [ -z "$DEST" ]; then DEST="/root/compustar-deploy"; fi
          rsync -avz --delete \
            --exclude ".git/" \
            --exclude ".github/" \
            --exclude ".export/" \
            --exclude "node_modules/" \
            --exclude ".venv/" \
            --exclude "__pycache__/" \
            -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }}" \
            ./ "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:$DEST/"

      # (Opcional) comandos de post-deploy — descoméntalos si aplican a tu proyecto
      - name: Post-deploy commands (optional)
        run: |
          DEST="${{ secrets.DEPLOY_PATH }}"
          if [ -z "$DEST" ]; then DEST="/root/compustar-deploy"; fi
          ssh -o StrictHostKeyChecking=no -p "${{ secrets.SSH_PORT }}" \
            "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" <<'EOF'
          set -e
          # cd "$DEST"
          # composer install --no-dev --optimize-autoloader
          # php artisan migrate --force
          # npm ci && npm run build
          # systemctl reload nginx || true
          EOF
