name: Sync repo to Google Drive

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Write rclone.conf from secret
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf
      
      - name: Write service account JSON from secret
        run: |
          mkdir -p ~/.config/rclone
          echo '${{ secrets.GDRIVE_SA_JSON }}' > ~/.config/rclone/sa.json
      
      - name: Create export
        run: |
          mkdir -p .export
          git rev-parse --short HEAD > .export/commit.txt
          DATE=$(date -u +"%Y-%m-%dT%H%M%SZ")
          zip -r ".export/source-${DATE}-${GITHUB_SHA}.zip" . \
            -x ".git/*" ".github/*" ".export/*"

      - name: Upload snapshot zip to github-sync
        run: |
          rclone copy .export "gdrive:github-sync" --progress

      - name: Mirror repo to repo-latest (clean copy)
        run: |
          rclone sync . "gdrive:github-sync/repo-latest" \
            --exclude ".git/**" --exclude ".github/**" --exclude ".export/**" \
            --delete-excluded --progress
